### PR TITLE
Updates for node, npm packages and serverless

### PR DESCRIPTION
**Pull request by sauy7**
Add package-lock.json to version control

### CODE REVIEW

**Comment by sauy7** [comment]
Work in progress version of rules.json
```
[
  "^/s/-/-/(.+)$ https://fishbrain.com/shop [RL]",
  "^/s/-/(.+)$ https://fishbrain.com/b/$1 [RL]",
  "^/s/(.+)/(.+)$ https://fishbrain.com/c/$1/$2 [RL]",
  "^/s/(.+)$ https://fishbrain.com/c/$1 [RL]",
  "^/shop/(.+)$ https://fishbrain.com/shop [RL]",
  "^/d$ https://fishbrain.com/shop [RL]",
  "^/welcome/landing$ https://fishbrain.com/shop/info/become-a-seller [RL]",
  "^/promo/apply-to-sell$ https://fishbrain.com/shop/info/become-a-seller [RL]",
  "^/promo/become-a-seller$ https://fishbrain.com/shop/info/become-a-seller [RL]",
  "^/new-retailer-account$ https://fishbrain.com/shop/info/become-a-seller [RL]",
  "^/contact_us/(.+)$ https://fishbrain.com/shop/info/contact-us [RL]",
  "^/promo/contact-us$ https://fishbrain.com/shop/info/contact-us [RL]",
  "^/orders/new$ https://fishbrain.com/cart [RL]",
  "^/orders/checkout$ https://fishbrain.com/checkout [RL]",
  "^/blog(.*)$ https://fishbrain.com/ [RL]",
  "^/article/terms-conditions$ https://fishbrain.com/terms-and-conditions [RL]",
  "^/promo/terms-and-conditions$ https://fishbrain.com/terms-and-conditions [RL]",
  "^/article/privacy-and-security$ https://fishbrain.com/privacy [RL]",
  "^/promo/privacy-policy$ https://fishbrain.com/privacy [RL]",
  "^/promo/faq$ https://fishbrain.helpshift.com/a/fishbrain---social-fishing-forecast-app/ [RL]",
  "^/promo/customer-service-escalation$ https://fishbrain.helpshift.com/a/fishbrain---social-fishing-forecast-app/ [RL]",
  "^/article/delivery-returns$ https://fishbrain.helpshift.com/a/fishbrain---social-fishing-forecast-app/ [RL]",
  "^/promo/old-faq$ https://fishbrain.helpshift.com/a/fishbrain---social-fishing-forecast-app/ [RL]",
  "^/promo/tax-policies$ https://fishbrain.com/shop/info/tax-policies [RL]",
  "^/promo/(.+)$ https://fishbrain.com/shop/promo/$1 [RL]"
]
```

**Review by dalen — APPROVED** [review]
lgtm. But there was some bug report on the repo regarding serverless-plugin-optimize. Potentially we should just remove that one. The lambda will be a tiny bit larger, but not a big issue really.

**Comment by dalen** [comment]
But currently this is being used on the regular fishbrain.com website. So would have to create new branches and deployments for the shop domain.

But could have something like `shop-production` and `shop-staging`

**Comment by sauy7** [comment]
For the shop staging environment we use fishbrain.staging.marketplacer.com, not our own domain. I will need to check with the fishunite team if we need to deploy a version for staging. My hunch is we won't need it. Rather, only a temporary version to test prior to launch next month.

**Pull request merged**
